In [1]:
import numpy as np


In [3]:
a=np.array([1,2,3])

In [5]:
print(type(a))

<class 'numpy.ndarray'>


In [7]:
print(a.shape)

(3,)


In [9]:
print(a[0],a[1],a[2])

1 2 3


In [11]:
# to chane element of array
a[0]= 5

In [15]:
print(a)

[5 2 3]


In [25]:
b=np.array([[1,2,3,4],[4,5,6,4]])

In [27]:
print(b.shape)

(2, 4)


In [31]:
print(b[0,0],b[0,1],b[0,2],b[0,3])

1 2 3 4


In [33]:
a=np.zeros((2,2))

In [35]:
print(a)

[[0. 0.]
 [0. 0.]]


In [41]:
b=np.ones((1,2,3))

In [43]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]]


In [45]:
b=np.ones((1,2))

In [47]:
print(b)

[[1. 1.]]


In [49]:
c=np.full((2,2),5)

In [51]:
print(c)

[[5 5]
 [5 5]]


In [59]:
d=np.eye(3) # identy matrix

In [61]:
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [65]:
e=np.random.random((2,2))

In [67]:
print(e)

[[0.85088588 0.1233299 ]
 [0.97565603 0.76303654]]


In [69]:
f=np.array(np.mat('1 2;3 4'))

In [71]:
print(f)

[[1 2]
 [3 4]]


In [73]:
g=np.array(np.mat('1 2;3 4'),subok=True)

In [75]:
print(g)

[[1 2]
 [3 4]]


In [77]:
a=np.arange(10)

In [85]:
print(a[2:5]) # slice

[[4 5 6]]


In [83]:
a=np.array([[1,2,3],[3,4,5],[4,5,6]])

In [95]:
print(a[1:])

[[3 4 5]
 [4 5 6]]


In [83]:
a=np.array([[1,2,3],[3,4,5],[4,5,6]])

In [97]:
print(a[...,1])

[2 4 5]


In [99]:
print(a[1,...])

[3 4 5]


In [101]:
print(a[...,1:])

[[2 3]
 [4 5]
 [5 6]]


In [103]:
a=np.array([[1,2],[3,4],[5,6]])
b=a[[0,1,2],[0,1,0]]

In [ ]:
print(y)